# Environment
FLASK_ENV: "DEVELOPMENT"

# Application configurations
SERVER_IP: "127.0.0.1:5000"

# Databases configurations
DB_URL: "mysql+mysqlconnector://arch:notsql@localhost:3306/glcaptest"
DB_CONN: "localhost"
DB_NAME: "glcaptest"
DB_USER: "arch"
DB_PASS: "notsql"

# Other folder path
DIR_ROOT: "/tmp/"
DIR_DATA: "testdata"
DIR_LOG: "log/filemanager.log"


